# Generated by Django 5.0.2 on 2026-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
